name: SWE Web App CI

on:
  push:
    branches: 
      - develop
      - master
      - feature/**
  pull_request:
    branches: 
      - develop
      - master
      - feature/**

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo content
      uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_LARAVEL }}
      run: |
        vendor/bin/phpunit -c phpunit.xml
        vendor/bin/php-coveralls -v
    - name: Slack Notification
      uses: homoluctus/slatify@v2.0.1
      if: failure()
      with:
        type: ${{ job.status }}
        job_name: 'CI Check'
        mention: 'here'
        mention_if: 'failure'
        channel: '#devops_software'
        username: 'CI Checker'
        url: ${{ secrets.SLACK_SW_WEBHOOK }}
        commit: true
        token: ${{ secrets.GITHUB_TOKEN }}
